# Generated by Django 2.0.1 on 2018-01-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Flim_Name', models.CharField(max_length=32)),
                ('Music_name', models.CharField(max_length=32)),
            ],
        ),
    ]
