# Generated by Django 2.0.1 on 2018-01-21 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_newlatterusers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewlatterUsers',
            new_name='join',
        ),
    ]
