# Generated by Django 2.0.1 on 2018-01-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180121_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie_history', models.IntegerField()),
                ('Theater', models.CharField(max_length=32)),
                ('most_wacth', models.CharField(max_length=32)),
            ],
        ),
    ]
